import Navbar from '@/components/UI/Header/Navbar';
import '../styles/globals.scss'
import { Poppins } from 'next/font/google'

const inter = Poppins({ weight: ["400", "600", "700"], style: ["normal"] }); 

// оставлено для лучших времен
//export const metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Navbar/>
        <main className='container mx-auto px-4'>{children}</main>
      </body>
    </html>
  );
}
